CREATE TABLE IF NOT EXISTS captaciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  cargo VARCHAR(255) NOT NULL,
  whatsapp VARCHAR(30) NOT NULL,
  email VARCHAR(255) NOT NULL,
  empresa VARCHAR(255) NOT NULL,
  num_clientes VARCHAR(50),
  pais VARCHAR(100),
  estado VARCHAR(100),
  ciudad_region VARCHAR(255),
  infraestructura VARCHAR(50),
  soluciones JSON NOT NULL,
  rsg_marcas JSON NOT NULL,
  rsg_marcas_otro VARCHAR(255),
  software_actual VARCHAR(50),
  software_otro VARCHAR(255),
  inconvenientes_sistema TEXT,
  expectativas TEXT,
  fecha_ingreso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_captaciones_fecha_ingreso (fecha_ingreso),
  INDEX idx_captaciones_email (email),
  INDEX idx_captaciones_deleted_at (deleted_at)
);
